### ISSUE TITLE
hello dear Hitomis 

### ISSUE THREAD

**Issue by moh241eng** [Hitomis/CircleMenu#10]
i have this Issues 
CircleMenu-master\cmlibrary\build.gradle 
No service of type Factory available in projectScopeService 
after open file 
problem in  
apply plugin: 'com.github.dcendents.android-maven'

apply plugin: 'com.android.library'
// JitPack Maven
apply plugin: 'com.github.dcendents.android-maven'
// Group
group='com.github.Hitomi'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
}

thank you and have nice day

**Comment by Hitomis** [comment]
Maven plug-in version is too old. update the maven plug-in version in the Project's build.gradle file
` classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'`

**Comment by moh241eng** [comment]
thank you dear 
Great work
