### ISSUE TITLE
想问您个问题

### ISSUE THREAD

**Issue by originzyf** [Hitomis/CircleMenu#12]
我现在的需求是双击屏幕上任意一点 弹出几个按钮  您能给点建议吗

**Comment by Hitomis** [comment]
Activity 的 根布局监听点击事件

**Comment by originzyf** [comment]
谢谢您的回复 是我没表述清楚 是这样 我在做一个白板功能  需要双击的时候根据我当时点击的xy轴坐标为圆心 打开和关闭这个按钮

**Comment by Hitomis** [comment]
根据你当前的问题，我想起码分为两个步骤
1、获取当前点击的坐标值 (x,y), 在该坐标的位置的父布局中添加 CircleMenu
2、打开 CircleMenu

我想你应该是步骤1不明白如何做：(view 表示 CircleMenu)
你可以将使用 view.setX() 和 view.setY() 两个方法将 一个 View 定位在坐标(x,y)处，注意这里的(x,y)是 view 的左上角坐标，并不是 View 的正中心坐标。定位到正中心，还需要校正坐标(x, y) 为 
(x - view.getWidth() / 2, y - view.getHeight() / 2)
