### ISSUE TITLE
How to remove padding

### ISSUE THREAD

**Issue by tellfa** [Hitomis/CircleMenu#2]
Hi, Thanks for this great library.
I want remove padding, i set menu in this position : 

```
        android:layout_alignParentBottom="true"
        android:layout_alignParentLeft="true"
```

but in this position show padding left and bottom! i want not padding in this menu, how can edit your CircleMenu.java for set padding=0 ? 

Thanks ❤️

**Comment by Hitomis** [comment]
@tellfa  Sorry!
I have not set the padding, the spacing you see is because the menu closes the animation needed before leaving the spacing.

Please look closely at the rotating animation of the close menu.

**Comment by tellfa** [comment]
@Hitomis , thnx man. how can i close menu with onBackPress ? I write if(menu.isShown()){} but i can't find close method for menu. how can it?

**Comment by Hitomis** [comment]
I forgot to add the methods openMenu & closeMenu.
thanks for you reminding~ now the code has been submitted.
you can update the code and try the following code again：

open the CircleMenu

```
        circleMenu.openMenu();
```

close the CircleMenu

```
        circleMenu.closeMenu();
```

**Comment by tellfa** [comment]
@Hitomis, Thnx bro ❤️
