### ISSUE TITLE
Close menu

### ISSUE THREAD

**Issue by tellfa** [Hitomis/CircleMenu#3]
Hi @Hitomis , i use this library. i write this code but when click on back button, not close the menu! when press back button close activity!

`@Override
    public void onBackPressed() {
        if (profile_circleMenu.isOpened()) {
            profile_circleMenu.closeMenu();
        }
        super.onBackPressed();
    }`

how can close menu with backButton? 

Thnx ❤️

**Comment by Hitomis** [comment]
Ha, please remove this line of code:
`super.onBackPressed();`

**Comment by tellfa** [comment]
Thnx @Hitomis , please release such as this library again 😄 ❤️

**Comment by Hitomis** [comment]
@tellfa 
The official version has been released and the README documentation has been updated
