### ISSUE TITLE
主按键图片

### ISSUE THREAD

**Issue by zhudeng** [Hitomis/CircleMenu#4]
当不设置主按键的图片资源时，它的引用为null，为何不创建一个默认的呢？

**Comment by Hitomis** [comment]
这是个众口难调的问题啊。CircleMenu 设计就是需要图标才能正常运作的控件。不过我应该处理一下当图标为空的情况。 就像 ListView ，如果你不设置 Adapter， ListView 不会报错，但是也没有数据显示。
thx~

**Comment by Hitomis** [comment]
现在修改为：如果没设置图标也不会报错
