### ISSUE TITLE
main icon is default empty

### ISSUE THREAD

**Issue by abbasalim** [Hitomis/CircleMenu#8]
hi,
my problem :
[http://uupload.ir/files/u3oq_demo.gif.gif](http://uupload.ir/files/u3oq_demo.gif.gif)
my code is 
`
 circleMenu = (CircleMenu) findViewById(R.id.circle_menu);
        circleMenu.setMainMenu(Color.parseColor("#FF4081"), R.mipmap.ic_more_vert_white, R.mipmap.eqiq_icon_cancel)
                .addSubMenu(Color.parseColor("#FF6A00"), R.mipmap.ic_bookmark_border_white_24dp)
                .addSubMenu(Color.parseColor("#8A39FF"), R.mipmap.ic_share)
                .addSubMenu(Color.parseColor("#30A400"), R.mipmap.abc_ic_ab_back)
                .addSubMenu(Color.parseColor("#FF4B32"), R.mipmap.dll)
                .addSubMenu(Color.parseColor("#258CFF"), R.mipmap.ic_action_pause)
                .setOnMenuSelectedListener(new OnMenuSelectedListener() {

                    @Override
                    public void onMenuSelected(int index) {

                    }

                }).setOnMenuStatusChangeListener(new OnMenuStatusChangeListener() {

            @Override
            public void onMenuOpened() {}

            @Override
            public void onMenuClosed() {}

        });
`

**Comment by Hitomis** [comment]
Bug has been fixed.
please update version v1.0.2.
